name: Build and test
on:
  push:
    branches:
      - main
jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-2025
    steps:
      - uses: actions/checkout@v7
      - name: Compile
        run: |
          cmake -B build
          cmake --build build
      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure
