name: CMake on multiple platforms

on:
  push:
    paths-ignore:
      - ".editorconfig"
      - ".gitignore"
      - "README.md"
      - "bench/**"
  pull_request:
    paths-ignore:
      - ".editorconfig"
      - ".gitignore"
      - "README.md"
      - "bench/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-26.04, windows-latest, macos-26]
        cpp_compiler: [clang++, g++, cl]
        build_type: [Release, Debug]
        exclude:
          - os: windows-latest
            cpp_compiler: g++
          - os: ubuntu-26.04
            cpp_compiler: cl
          - os: macos-26
            cpp_compiler: cl
          - os: macos-26
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v7

    - name: Configure CMake (Linux, Windows w/o MSVC, macOS w/o Clang)
      if: >
        matrix.cpp_compiler != 'cl' &&
        (
          matrix.os != 'macos-26' ||
          matrix.cpp_compiler != 'clang++'
        )
      run: >
        cmake -B ${{ github.workspace }}/build -G Ninja
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Configure CMake (macOS, Clang)
      if: matrix.os == 'macos-26' && matrix.cpp_compiler == 'clang++'
      run: >
        cmake -B ${{ github.workspace }}/build -G Ninja
        -DCMAKE_CXX_COMPILER=$(brew --prefix llvm@20)/bin/clang++
        -DCMAKE_OSX_SYSROOT="$(xcrun --sdk macosx --show-sdk-path)"
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Configure CMake (Windows, MSVC)
      if: matrix.os == 'windows-latest' && matrix.cpp_compiler == 'cl'
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}


    - name: Build
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ github.workspace }}/build
      run: ctest --build-config ${{ matrix.build_type }}
